# Generated by Django 5.1.3 on 2024-11-28 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzencode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgdb',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dzencode.msgdb'),
        ),
        migrations.AddField(
            model_name='msgdb',
            name='published_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
