# Generated by Django 5.1.3 on 2024-11-28 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzencode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgdb',
            name='published_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
