# Generated by Django 5.1.3 on 2024-11-29 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzencode', '0003_msgdb_is_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgdb',
            name='has_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='msgdb',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='msgdb',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='msgdb',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dzencode.user'),
        ),
    ]
