# Generated by Django 5.1.3 on 2024-12-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzencode', '0005_user_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$JzlsA7Vboh14R23juBjURW$4Rb3TMfU3tM0hM61wRAdrP9vT2+LaCM+GbyZBkMzfSQ=', max_length=128),
        ),
    ]
