# Generated by Django 5.1.3 on 2024-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzencode', '0006_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$8gRmczcRneDvtvrWoQ2pcx$VQAVsEU6VeZRQkptkr+St7nhT0GNKLzFTiQGumHbw90=', max_length=128),
        ),
    ]
